version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      - echo Installing Maven...
      - apt-get update -y
      - apt-get install maven -y
  build:
    commands:
      - echo Building the project...
      - mvn clean install
artifacts:
  files:
    - target/*.jar
